### ISSUE TITLE
A not-found error

### ISSUE THREAD

**Issue by Tony-Dash** [ovh/sv2chisel#2]
Hello, thank you for this wonderful project. I am having following error.Will you please guide and help me?

**Describe the bug**
Since sv2chisel and sv2chisel-helpers are currently not available on maven central, could you please show how can I solve this problem?

**Additional context**
[warn] Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.ovhcloud:sv2chisel_2.13:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/com.ovhcloud/sv2chisel_2.13/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/ovhcloud/sv2chisel_2.13/0.1.0-SNAPSHOT/sv2chisel_2.13-0.1.0-SNAPSHOT.pom

Thank you again.

**Comment by johnsbrew** [comment]
Hi @Tony-Dash and thank you for your interest in sv2chisel.

I indeed really need to set up a proper release with publication to maven central.

In the meantime, the process to make available sv2chisel and sv2chisel-helpers locally is the following:
```bash
git clone  https://github.com/ovh/sv2chisel.git
cd sv2chisel
sbt '; publishLocal ; helpers/publishLocal'
```


I don't now if you've already started to use sv2chisel because I also need to update the README 😬
There is now a proper CLI based on a config file which I plan to release as binary executable, in addition to API usage.
For API usage, see the (slightly updated) example here 
https://github.com/ovh/sv2chisel/blob/master/src/main/scala/sv2chisel/AppExample.scala

For CLI usage,  enter sbt once for all with `sbt` command.
Then in sbt `runMain sv2chisel.Main -c config.yml`

Here is an example for config.yml :
https://github.com/ovh/sv2chisel/blob/master/src/main/resources/project/config.yml#L5-L11

For more details about CLI options, you can look at the output of `runMain sv2chisel.Main --help`

Please let me know if you need further information and do not hesitate to raise usage issues!

**Comment by Tony-Dash** [comment]
@johnsbrew I haven't started using your creative sv2chisel because of the issue I raised.
It would be very convenient for me learning Chisel if the translator could work. I will follow your instructions and do some try. 
Thank you so much for your reply.

**Comment by johnsbrew** [comment]
@Tony-Dash 
I am very curious to hear about your use of sv2chisel as a support to learn chisel!
I think you would benefit anyway from the numerous learning resource provided by the chisel community https://www.chisel-lang.org/chisel3/docs/resources/resources.html with in particular the online bootcamp to get started.

To help you with this project, I am glad to announce that I have just released sv2chisel on maven central along with a stand-alone sv2chisel application here on github: https://github.com/ovh/sv2chisel/releases/tag/v0.1.0-RC2

**Comment by johnsbrew** [comment]
Closing this with release 0.5.0 and up-to-date documentation.
@Tony-Dash did you finally manage to play with sv2chisel ?
The release provides native binaries for a smoother user-experience !

**Comment by Tony-Dash** [comment]
@johnsbrew I'm sorry to reply too late for some reasons. Yeah, I did play with sv2chisel and translate some simple module without any problem. And according to your suggestion, I'm now learning chisel by chisel community. You're an excellent and wonderful person, thanks so much!
